@startuml
title Sequence Diagram: Report

actor Manager
participant "SIMKEL" as System
database "Database" as DB
Manager -> System: Membuka Dashboard
activate System
System --> DB: SELECT * FROM permohonan
activate DB
DB --> System: Hasil Data Permohonan
deactivate DB
System --> Manager: Tampilkan Dashboard
deactivate System
Manager -> System: Filter Laporan
activate System
System --> DB: SELECT * FROM permohonan WHERE filter = ?
activate DB
DB --> System: Hasil Data Filtered
deactivate DB
System --> Manager: Tampilkan Laporan Filtered
deactivate System
Manager -> System: Memilih Permohonan
activate System
    System -> DB: SELECT * FROM permohonan WHERE id = ?
    activate DB
    DB --> System: Konfirmasi Select
    deactivate DB
    System --> Manager: Tampilkan Data Permohonan
    deactivate System
@enduml
